unique_ids:
  assets:
    standard-page.html: Q3QO6SVCSYGG2URQPHD2WQN53IJYWBMT
    theme.css: WZK5YAI72HXBAVF2NY77323MVSKI5HGU
  forms:
    Form1: RXKECMZN34MQAHDRK6EPIICDWR6S3KGX
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: K3BJP54LLIFUNBZKPJQNF3SQ3PXH3K3L
